spring:
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。

  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        ## system-server 服务
        - id: system-admin-api # 路由的编号
          uri: grayLb://system-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/system/**
          filters:
              - RewritePath=/admin-api/system/v3/api-docs, /v3/api-docs # 配置，保证转发到 /v3/api-docs
        - id: system-app-api # 路由的编号
          uri: grayLb://system-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/system/**
          filters:
              - RewritePath=/app-api/system/v3/api-docs, /v3/api-docs
        ## infra-server 服务
        - id: infra-admin-api # 路由的编号
          uri: grayLb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/infra/**
          filters:
              - RewritePath=/admin-api/infra/v3/api-docs, /v3/api-docs
        - id: infra-app-api # 路由的编号
          uri: grayLb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/infra/**
          filters:
              - RewritePath=/app-api/infra/v3/api-docs, /v3/api-docs
        - id: infra-spring-boot-admin # 路由的编号（Spring Boot Admin）
          uri: grayLb://infra-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin/**
        ## book-server 服务
        - id: book-admin-api # 路由的编号
          uri: grayLb://book-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/book/**
          filters:
            - RewritePath=/admin-api/book/v3/api-docs, /v3/api-docs
        - id: book-app-api # 路由的编号
          uri: grayLb://book-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/book/**
          filters:
            - RewritePath=/app-api/book/v3/api-docs, /v3/api-docs
        ## book-lend-server 服务
        - id: book-lend-admin-api # 路由的编号
          uri: grayLb://book-lend-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/book/lend/**
          filters:
            - RewritePath=/admin-api/book/lend/v3/api-docs, /v3/api-docs
        - id: book-lend-app-api # 路由的编号
          uri: grayLb://book-lend-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/book/lend/**
          filters:
            - RewritePath=/app-api/book/lend/v3/api-docs, /v3/api-docs
        ## book-user-server 服务
        - id: book-user-admin-api # 路由的编号
          uri: grayLb://book-user-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/book/user/**
          filters:
            - RewritePath=/admin-api/book/user/v3/api-docs, /v3/api-docs
        - id: book-user-app-api # 路由的编号
          uri: grayLb://book-user-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/app-api/book/user/**
          filters:
            - RewritePath=/app-api/book/user/v3/api-docs, /v3/api-docs

      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-api/system 前缀

knife4j:
  # 聚合 Swagger 文档，参考 https://doc.xiaominfo.com/docs/action/springcloud-gateway 文档
  gateway:
    enabled: true
    routes:
      - name: system-server
        service-name: system-server
        url: /admin-api/system/v3/api-docs
      - name: infra-server
        service-name: infra-server
        url: /admin-api/infra/v3/api-docs
      - name: book-server
        service-name: book-server
        url: /admin-api/book/v3/api-docs
      - name: book-lend-server
        service-name: book-lend-server
        url: /admin-api/book/lend/v3/api-docs
      - name: book-user-server
        service-name: book-user-server
        url: /admin-api/book/user/v3/api-docs